### ISSUE TITLE
Blood sample coherence

### ISSUE THREAD

**Issue by kofferhue** [yellow-bird-consult/game_feedback#1]
I dont know yet how to handle certain blood profiles for some diseases which have optional conditions coded in their history:

- past medical history informations which require a certain blood profile would be for example chronic kidney disease stage 3 => renal profile with elevated krea, reduced gfr...

**Comment by CarolineMorton** [comment]
I just need a list of these and what blood profiles are affected, and the changes. Elevated glucose and HbA1C in type 2 diabetes, and elevated creatinine in CKD 3 is already coded into the backend. If there any others, just let me know.

**Comment by kofferhue** [comment]
Okay, these were the ones I was thinking of mainly. When I come across other conditions where this would apply, I put them on a list. Thanks Caroline!
